# Jekyll Site Configuration for sungminkg.github.io

# Basic Site Settings
remote_theme: academicpages/academicpages.github.io
locale: "en-US"
title: "Sungmin Kang"
title_separator: "-"
name: &name "Sungmin Kang"
description: &description "M.S. student in ECE at USC"
url: "https://sungminkg.github.io"
baseurl: ""
repository: "sungminkg/sungminkg.github.io"

# Author Profile (sidebar)
author:
  avatar: "SungminKang.jpg"
  name: "Sungmin Kang"
  pronouns: "he/him"
  bio: "M.S. student in Electrical and Computer Engineering at USC"
  location: "Los Angeles"
  employer: "University of Southern California"
  email: "kangsung@usc.edu"
  github: "sungminkg"
  linkedin: "https://www.linkedin.com/in/sungmin-kang-1999y64/"

# Site Settings
future: true
read_more: "disabled"
breadcrumbs: false
talkmap_link: false
words_per_minute: 160

# Comments
comments:
  provider: false

# Feeds
atom_feed:
  hide: false

# Markdown Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults for collections/pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Include folders
include:
  - .htaccess
  - _pages
  - files

# Exclude from build
exclude:
  - "*.sublime-*"
  - .bundle
  - .github
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - package.json*
  - Rakefile
  - log
  - tmp

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Permalink
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Archive paths
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
